# Generated by Django 3.0.6 on 2022-06-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_chart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='content',
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_price_td',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_price_tm',
            field=models.CharField(default='', max_length=255),
        ),
    ]
