# Generated by Django 3.0.6 on 2022-06-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_chart', '0002_auto_20220616_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_price_td',
            field=models.IntegerField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_price_tm',
            field=models.IntegerField(default='0', max_length=255),
        ),
    ]
