# Generated by Django 3.0.6 on 2022-06-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_chart', '0003_auto_20220616_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_price_td',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_price_tm',
            field=models.IntegerField(default='0'),
        ),
    ]
