# Generated by Django 3.0.6 on 2022-06-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_chart', '0004_auto_20220616_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_text', models.CharField(default='', max_length=255)),
                ('stock_title', models.TextField()),
                ('stock_url', models.TextField()),
            ],
        ),
    ]
